version: "3"

services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ddd-pgsql:/var/lib/postgresql/data
volumes:
  ddd-pgsql:
    driver: local
